### ISSUE TITLE
Problema com Delete e Id's

### ISSUE THREAD

**Issue by Besourinho123** [Besourinho123/TCC-samu#3]
Pessoal, estou com um pequeno problema quando deleta uma notícia e eu suponho que acontecerá o mesmo problema quando for com os cursos.

Quando deleta uma noticia, visto que o id é auto_increment, quando o usuario for ler a ultima postada, o id sai fora de ordem numerica, assim a função não consegue requistar o id da noticia que foi constatada.

Atenciosamente, Barbosa 👍

**Comment by MarrentaxD** [comment]
Tudo ok já! 👍
